# Generated by Django 5.2.4 on 2025-07-06 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Prompt content (Bangla)')),
                ('priority', models.IntegerField(default=1, help_text='Integer for weighted randomness')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='URL of the uploaded image from Cloudinary', max_length=500)),
                ('public_id', models.CharField(help_text='Cloudinary public ID for the image', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('unverified', 'Unverified')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Notes from moderator', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.prompt')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
